#!/bin/sh
set -e
SCRIPTDIR="$(readlink -f "$(dirname "$0")")"

ISSUE="$(cat /etc/issue 2>/dev/null)" || true
LSB_RELEASE="$(cat /etc/lsb-release 2>/dev/null)" || true
VCORES="$(cat /proc/cpuinfo  | grep 'core id' | wc -l)"

LIBS=$(ls "$SCRIPTDIR/libs" | sort)
LIBNAMES=$(echo "$LIBS" | sed 's,^[0-9]*-,,')
for LIB in $LIBS; do
  . $SCRIPTDIR/libs/$LIB
done
for LIB in $LIBSNAMES; do
  "${LIB}_update"
done
nix-collect-garbage -d
