#!/bin/sh
cd "$(readlink -f "$(dirname "$0")")"

add_user () {
  NAME="$1"
  USERID="$2"
  GROUPID="$3"
  DES="$4"
  sed -i '/^$NAME/d' /etc/passwd
  echo "$NAME:x:$USERID:$GROUPID:$DES:/var/empty:/usr/sbin/nologin" >> /etc/passwd
}

quassel_install () {
  cp "$SCRIPTDIR/ref/quassel/quassel.conf" /etc/init/quassel.conf
  add_user quassel 1279000000 55534 "Quassel Daemon User"
  mkdir -p -m 0700 /var/lib/quassel
  chown quassel /var/lib/quassel
  quassel_update
}

quassel_update () {
  install_pkg pkgs.quasselDaemon -r -p /nix/var/nix/profiles/quassel
  service quassel restart
}

quassel_cleanup_old () {
  sed -i '/quassel/d' /etc/passwd
  rm -f /etc/init/quassel.conf
  rm -rf /var/lib/quassel
}

quassel_cleanup_final () {
  return 0
}
