#!/bin/sh
cd "$(readlink -f "$(dirname "$0")")"

add_user () {
  NAME="$1"
  USERID="$2"
  GROUPID="$3"
  DES="$4"
  sed -i '/^$NAME/d' /etc/passwd
  echo "$NAME:x:$USERID:$GROUPID:$DES:/var/empty:/usr/sbin/nologin" >> /etc/passwd
}

quassel_install () {
cat >/etc/init/quassel.conf <<EOF
start on runlevel [2345]
stop on runlevel [!2345]

respawn

exec /nix/var/nix/profiles/quassel/bin/quasselcore
EOF
  add_user quassel 1279000000 55534 "Quassel Daemon User"
  mkdir -p -m 0700 /var/lib/quassel
  chown quassel /var/lib/quassel
  quassel_update
}

quassel_update () {
  nix-env -p /nix/var/nix/profiles/quassel -iA nixpkgs.pkgs.kde4.quasselDaemon
  service quassel restart
}

quassel_cleanup_old () {
  sed -i '/quassel/d' /etc/passwd
  rm -f /etc/init/quassel.conf
  rm -rf /var/lib/quassel
}

quassel_cleanup_final () {
  return 0
}
